### ISSUE TITLE
New Working item Cloud Optimized GeoTIFF community standard

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/geotiff#102]
The Testbed 17 has a proposal for a new draft specification for COG: https://gitlab.ogc.org/ogc/T17-D046-COG-Specification-ER/-/tree/master/standardDrafts/COG

We would like to move it to an OGC community standard in this group. The process is a bit different form other community standards. There is no comprehensive documentation of the COG format anywhere, so we cannot adopt any preexisting document directly. It was needed to collect all the existing information and reformatted it into clear requirements.

**Comment by joanma747** [comment]
Step that we will follow

* We need to document what the community is doing as a first step (v1.0)
* We need to evaluate the value of the TMS support (what use cases it represent)
* In a second step (v1.1) we could add the TMS support at later stage

**Comment by joanma747** [comment]
The repository for this working item is:
https://github.com/opengeospatial/CloudOptimizedGeoTIFF

**Comment by joanma747** [comment]
The repository is now populated with the materials created from Testbed17. The intention is to keep them aligned until the end of Testbed 17 except on the parts where the Testbed17 was "creative" (mainly in relation to 2D-TMS) that has been removed to go back to the original COG direction. Afterwards, the work will exclusively continue in the GeoTIFF.SWG.

**Comment by desruisseaux** [comment]
Should we close this issue since it is done?
