### ISSUE TITLE
Delete merged branches

### ISSUE THREAD

**Issue by desruisseaux** [opengeospatial/geotiff#115]
The [list of branches](https://github.com/opengeospatial/geotiff/branches/all) currently contains 18 merged or closed branches, which are identified as "stalled" by GitHub. We should delete at least the merged branches. It will not delete the pull request, which still archived on GitHub as today, neither loose any commits since they are merged.

**Comment by joanma747** [comment]
done

**Comment by desruisseaux** [comment]
Thanks!
