### ISSUE TITLE
Lunar example for spec appendix

### ISSUE THREAD

**Issue by thareUSGS** [opengeospatial/geotiff#15]
Perhaps placed in the informative " D.8.2 Less Common Examples " section (or an appendix).

Goals for this addition is to display a very simple extraterrestrial example (e.g. a spherical Moon). But this example, often requiring "User-Defined", shows how more custom Earth-base examples could also be defined. I think it highlights the flexibility for a GeoTiff label.

Note this example (using listgeo), is showing the header values as mapped strings instead of the original short Integer. e.g. GTModelTypeGeoKey = ModelTypeProjected (which is really mapped from value 1) see: 
https://github.com/ufz/geotiff/blob/473ab941f80592ada6a226ec666d7e6e8f79c21b/geonames.h#L67
- And where "User-Defined" is numerically mapped to value 32767

Question -  are showing the strings enough (as below) or should we show the integers?

$ listgeo Lunar_LRO_LOLA_Global_LDEM_118m_Mar2014.tif
```
Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTiepointTag (2,3):
         0                 0                 0
         -5458203.076608   2729101.538304    0
      ModelPixelScaleTag (1,3):
         118.4505876       118.4505876       0
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,29): "SimpleCylindrical Moon"
      GeographicTypeGeoKey (Short,1): User-Defined
      GeogCitationGeoKey (Ascii,124): "GCS Name = Moon 2000|Datum = D_Moon_2000|Ellipsoid = Moon_2000_IAU_IAG|Primem = Reference_Meridian|AUnits = Decimal_Degree|"
      GeogGeodeticDatumGeoKey (Short,1): User-Defined
      GeogAngularUnitSizeGeoKey (Double,1): 0.0174532925199433
      GeogEllipsoidGeoKey (Short,1): User-Defined
      GeogSemiMajorAxisGeoKey (Double,1): 1737400          
      GeogSemiMinorAxisGeoKey (Double,1): 1737400          
      GeogPrimeMeridianLongGeoKey (Double,1): 0                
      ProjectedCSTypeGeoKey (Short,1): User-Defined
      ProjectionGeoKey (Short,1): User-Defined
      ProjCoordTransGeoKey (Short,1): CT_Equirectangular
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      ProjStdParallel1GeoKey (Double,1): 0                
      ProjFalseEastingGeoKey (Double,1): 0                
      ProjFalseNorthingGeoKey (Double,1): 0                
      ProjCenterLongGeoKey (Double,1): 0                
      ProjCenterLatGeoKey (Double,1): 0                
      End_Of_Keys.
   End_Of_Geotiff.
...

```

**Comment by tedhabermann** [comment]
Thanks to Trent for this example. I have converted it to ASCIIDoc in the file annex-lunar.adoc

**Comment by tedhabermann** [comment]
Open to suggestions about text strings vs. integers

**Comment by EmDevys** [comment]
Ted, et al
Unsure I understand correctly ..

In GeoTIFF spec. key values of type SHORT use the Geokeys referenced from GeoKeyDirectoryTag.
key-values which are not of type SHORT are either: GeoDoubleParamsTag or GeoAsciiParamsTag (for strings).

What is this discussion about text strings vs integers ?

Emmanuel

De : Ted Habermann [mailto:notifications@github.com]
Envoyé : lundi 9 juillet 2018 16:52
À : opengeospatial/geotiff
Cc : Subscribed
Objet : Re: [opengeospatial/geotiff] Lunar example for spec appendix (#15)


Open to suggestions about text strings vs. integers

**Comment by tedhabermann** [comment]
Emmanuel,

My bad. Forgot to synch with github… Lunar example is at https://github.com/opengeospatial/geotiff/blob/master/GeoTIFF%20Standard/standard/annex-lunar.adoc

Ted

==== Ted Habermann ========================
Director of Earth Science, The HDF Group
Voice: (217) 531-4202
Email: thabermann@hdfgroup.org<mailto:thabermann@hdfgroup.org>
==== HDF: Software That Powers Science ====

**Comment by EmDevys** [comment]
Thanks Ted

De : Ted Habermann [mailto:notifications@github.com]
Envoyé : mardi 10 juillet 2018 20:05
À : opengeospatial/geotiff
Cc : Emmanuel Devys; Comment
Objet : Re: [opengeospatial/geotiff] Lunar example for spec appendix (#15)

Emmanuel,

My bad. Forgot to synch with github… Lunar example is at https://github.com/opengeospatial/geotiff/blob/master/GeoTIFF%20Standard/standard/annex-lunar.adoc

Ted

==== Ted Habermann ========================
Director of Earth Science, The HDF Group
Voice: (217) 531-4202
Email: thabermann@hdfgroup.org<mailto:thabermann@hdfgroup.org>
==== HDF: Software That Powers Science ====

**Comment by tedhabermann** [comment]
All,

I am getting ready for multiple presentations next week at the ESIP meeting so geotiff has slipped to the back burner…

Ted

==== Ted Habermann ========================
Director of Earth Science, The HDF Group
Voice: (217) 531-4202
Email: thabermann@hdfgroup.org<mailto:thabermann@hdfgroup.org>
==== HDF: Software That Powers Science ====
