### ISSUE TITLE
New ESPG Releases

### ISSUE THREAD

**Issue by tedhabermann** [opengeospatial/geotiff#2]
This problem is described by Frank Warmerdam on the [Refining GeoTIFF](http://trac.osgeo.org/geotiff/wiki/RefiningGeoTIFF) page.

The [GeoTIFF Specification](http://www.remotesensing.org/geotiff/spec/geotiffhome.html) was based on the EPSG database in release at the time. Since then the EPSG database has grown and to a limited extent been refactored. While it was not exactly clear how this related to GeoTIFF? the accepted industry practice has been to accept newer EPSG PCS and GCS codes even though they are not explicitly listed in the GeoTIFF? specification (ie. sections 6.3.2, 6.3.3 and 6.3.4). It is suggested that this be codified into the GeoTIFF? specification. We should also likely update sections 6.3.x to reflect a current set of codes or alternatively remove them in favor of a reference to EPSG with a few examples for clarification.

**Comment by EmDevys** [comment]
Done in revision 1.1. Also suppressed and deprecated values are documented in annexes.
