### ISSUE TITLE
Convert Word template to ASCII Doc - Chuck

### ISSUE THREAD

**Issue by tedhabermann** [opengeospatial/geotiff#29]

**Comment by cmheazel** [comment]
Initial conversion of GeoTIFFinOGCtemplate_with-EPSG-changes_RL-2018-05-14.docx to AsciiDoc is complete.  The resulting spec needs some re-formatting, but on the whole is surprisingly good.  Currently working on synchronizing my local GitHub project with the GitHub server.

**Comment by tedhabermann** [comment]
Great job Chuck - I look forward to making changes in the "new" world!

**Comment by cmheazel** [comment]
There is a new AsciiDoc branch.  Take a look.  If you are happy with it, I will merge it into Master.  This branch includes an AsciiDoc version of the spec with the exception of Annex D and E.

**Comment by tedhabermann** [comment]
You are right - in general looks pretty good. I think a merge is fine. 

We will drop Annex E from the document. Is there a future for Annex D?

**Comment by cmheazel** [comment]
I have the raw AsciiDoc for Annex D.  I just have to do the format clean-up.  Since it is not normative, I figured that for a lower priority.
