### ISSUE TITLE
Baseline the 1995 Version

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#42]
The current draft is not sufficient to replace the 1995 version.  Update with additional descriptive text and validate that all requirements are included.

**Comment by RogerLott** [comment]
This post covers not only this issue but also several others (e.g. EPSG codes, vertical). 

I have redrafted those parts of the document that describe Model CRS including EPSG codes. This is more than just a simple editing of the 1995 spec., but, I believe, remains within the spirit of this port. I  attach three docs:
1. 2018-12-18 pdf with numerous corrections shown by sticky notes and highlighting. (Highlighting normally means delete what is there and replace with sticky note comment.
2. Word doc with complete re-write of clause 7 Model CRS requirements.
3. Word doc with complete rewrite of Annex B.5.3 (Model CRS) and B.5.4 (EPSG stuff), also with three additional proposed annexes.

**Comment by RogerLott** [comment]
See post just made to issue #52. Should have been here!

**Comment by EmDevys** [comment]
Should now be fixed, all material of interest should be incorporated.
