### ISSUE TITLE
Validate EPSG codes

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#52]
Check the EPSG code ranges in the GeoTIFF requirements against the EPSC registry.

**Comment by RogerLott** [comment]
This post covers not only this issue but also several others including #7 (Vertical) and #52 (EPSG codes).

I attach 3 documents which collectively address the description of Model CRS and EPSG codes:
1. 2018-12-18 pdf annotated with corrections and edits using highlight and sticky notes. In general highlighted text should be replaced by that in the adjacent sticky note.
2. Model CRS requirements (clause 7) completely re-written.
3. Description of Model CRS (Annex B.5.3) and EPSG codes (Annex B.5.4) both completely re-written, together with three new suggested Annexes (Map projection codes, recommendations for describing compound and geographic 3D CRSs, and a summary list of all key codes and names).

The re-writes I believe improve the description of CRS stuff, which in the 1995 doc was (in my view) somwhat confusing, but I believe retains the spirit of this 'minimum change' port.

[GeoTiff 2018-12-18 RL CRS and EPSG edits.pdf](https://github.com/opengeospatial/geotiff/files/2717568/GeoTiff.2018-12-18.RL.CRS.and.EPSG.edits.pdf)
[GeoTIFF 2018-12-18 RL clause 7 CRS edits.docx](https://github.com/opengeospatial/geotiff/files/2717569/GeoTIFF.2018-12-18.RL.clause.7.CRS.edits.docx)
[GeoTIFF 2018-12-18 RL annex CRS edits.docx](https://github.com/opengeospatial/geotiff/files/2717570/GeoTIFF.2018-12-18.RL.annex.CRS.edits.docx)

**Comment by EmDevys** [comment]
Even, all
I focus on your comment ER4 on GeoTIFF.2018-12-18.RL.clause.7.CRS.edits_remarks_ERO.docx: "There are “GeoTIFF” files which have only ModelTiepointTag and ModelPixelScaleTag without any CRS indication; do we want to exclude them from being valid GeoTIFF files ? Same remark for GTModelTypeGeoKey".
My view of geoTIFF is (was) to associate Raster space to Model space, therefore (implicitly) to specify the ModelSpace (by means of CRS documentation). The 1995 specification was not constraining to this, but I can't understand the use case of any Transformation without the Model space definition. If there are such GeoTIFF files, do you know for which usage / use case such GeoTIFF files could help?
Would probably help to decide whether to allow this (in version 1.1) or not, as well as inversion 1.0 (for backward compatibility reason)

**Comment by RogerLott** [comment]
[GeoTIFF.2018-12-18.RL.clause.7.CRS.edits_remarks_ERO_RLcomment.docx](https://github.com/opengeospatial/geotiff/files/2722271/GeoTIFF.2018-12-18.RL.clause.7.CRS.edits_remarks_ERO_RLcomment.docx)

Some further comments on @rouault comments in GeoTIFF.2018-12-18.RL.clause.7.CRS.edits_remarks_ERO.docx

**Comment by cmheazel** [comment]
Pull request #65 (merged 1/11/19) should address all comments and changes discussed in this issue.

**Comment by EmDevys** [comment]
Inputs from Word documents (provided by Roger Lott) have been incorportated after adjustments (clause 7 and Annexes B-E).
Resulting draft is to be checked.
For conventions in Annex E and their generalisation, to be discussed before final decision and closing.

**Comment by EmDevys** [comment]
Inputs from Word document (provided by Roger Lott) have been incorportated, after review of draft
[GeoTIFF 2019-01-20 RLcomment.docx](https://github.com/opengeospatial/geotiff/files/2780573/GeoTIFF.2019-01-20.RLcomment.docx)
