### ISSUE TITLE
GeoKey Requirement Cleanup

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#54]
This is an issue to capture all clean-up tasks on the GeoKey requirements.

**Comment by cmheazel** [comment]
"But I noticed you are using wording like "Note: Original ranges were...." which you might want to change to "Note: 1.0 ranges were...."

**Comment by cmheazel** [comment]
Address mandatory vs. optional GeoKeys and Tags.

**Comment by cmheazel** [comment]
Make sure all dependencies between GeoKeys are correctly captured.

**Comment by EmDevys** [comment]
Should now be corrected in revision 1.1
