### ISSUE TITLE
Revised GeoTIFF specification strategy (handling existing 1.0 and/or 1.1 GeoTIFF versions)

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/geotiff#60]
GeoTIFF 1995 (version 1.0) specification is available online (http://geotiff.maptools.org/spec/geotiff6.html) and has some well-known issues which have been identified, discussed and solved by software according to some best practices.
We need to do some cleaning in the minor revision (which should be 1.1) as well as some clarification for handling raster representing vertical information.
We (Active SWG members) have in mind the requirement for "backward compatibility", but have to do some necessary changes, and the specification will be duly referenced as 1.1 (and documented as such by GeoKeyDirectoryTag.keyRevisionValue (1)  and GeoKeyDirectoryTag.minorRevisionValue (1)).
In order to simplify this specification, the current orientation is specify ONLY the 1.1 version requirements, which would allow nearly all (hopefully) of existing GeoTIFF 1.0 files (when reading a file).

We see no value in developing 2 versions, which would propagate (under the OGC wing) the existing 1.0 specification and its issues (also resulting in issues for testing conformance), and also develop a cleaned and modernized (as regards the use of EPSG register codes) (with consistent test suite). This would also results in duplication of efforts / resources (that the SWG does not seem to be able of).
We evaluated the option of having a "2 in 1" specification, with requirements that are common (most of them), distinct requirements (for versions 1.0 and 1.1) – some of them - and new ones (for version 1.1  only). This option appears to complexify a specification which is already complex.

Therefore the editor team presently proposes to specify only the 1.1 version requirements, which should allow the reading (and possibly also writing) of GeoTIFF files according to the 2 versions.
Hopefully there is no objection on this, otherwise please notify shortly with rationale and proposal of an improved strategy (as well as contribution to editing work).

**Comment by cmheazel** [comment]
@EmDevys I have no objection in principle, but I caution against scope creep.  Version 1.1 should only include changes where the 1995 version is either out of date or clearly wrong.

**Comment by EmDevys** [comment]
Proposed decision: to specify only the 1.1 version requirements, which should allow the reading of GeoTIFF 1.0 files - except those using suppressed tags (as well as version 1.1 files).
This minor revision 1.1 will document changes to 1.0 version.
