### ISSUE TITLE
Remark on standard draft Jan 16 2019: GeoKeyDirectoryTag.minorRevisionValue

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geotiff#69]
GeoKeyDirectoryTag.minorRevisionValue mentions "The MinorRevision for this standard SHALL be O or 1.

0 = 1995 version

1 = 2019 version"

This is probably implied, but we should probably add some comment that files following the requirement of the document SHOULD use minorRevisionValue = 1. Otherwise it might be difficult for a GeoTIFF reader to know with which set of rules interpreting the vertical part in particular.

Or perhaps we should rewrite this
```
The MinorRevision for this standard SHALL be 1

NOTE: the value 0 was used for files following the "Ritter, Niles & Ruth, Mike, GeoTIFF Format Specification, October 31, 1995"
```

**Comment by EmDevys** [comment]
I am wandering whether we should not allow 0 in case the file is fully compliant with legacy 1.0 (for ex. when there is no Vertical GeoKey).
Would any of these 2 options make sense ?
1- The MinorRevision for this standard SHALL be 1 in case VerticalGeoKey is used
2- The MinorRevision for this standard SHOULD be 1 if the GeoTIFF tags content is using the specific characteristics of this version 1.1 (e.g. if VerticalGeoKey is used or EPSG codes not avaialble in GeoTIFF 1.0) and SHOULD be 0 if the GeoTIFF tags or tags content are using values / codes that are suppressed in this version?
Urgent: feedback required!

**Comment by cmheazel** [comment]
Add a discussion of 1.0 vs. 1.1 in the Compliance section

**Comment by EmDevys** [comment]
Also cf. Max Martinez comment on 30 April 2019.
Proposal to add a note in this requirement table, such as : 
0 : GeoTIFF 1.0 version. Accepted for existing files (GeoTIFF 1.0)  that do not use values / codes that are suppressed in this version
1 = this version 1.1. Recommended for production / writing a GeoTIFF file according to this standard (and developing software). Shall be used for files using VerticalGeoKey and/or EPSG codes not covered by GeoTIFF 1.0
