### ISSUE TITLE
Remark on standard draft Jan 16 2019: editor

### ISSUE THREAD

**Issue by rouault** [opengeospatial/geotiff#71]
In the top of the document, "Editor: " still refers to Ted. Do we want to update this ?

In "Annex G: Revision History", the editor of v0.1 is "G. Editor". Shouldn't that be Ted ?

**Comment by EmDevys** [comment]
Good question: who is the editor? IMHO this is teamwork: Ted initiated, Chuck is the Editor / adminsitrator of this github version, Roger is a key contributor on geodetic components (including relation with EPSG), Even and myself are key contributors.
IMHO, we should reflect this in identifying the editor. Each of the 5 mentioned above should be cited.
Does it make sense? Any objection?
