### ISSUE TITLE
Projection Parameters

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#88]
While the original specification offers some example coordinate systems with projection parameters (ie. 3.1.3 Lamber Conformal Conic Aeronautical Chart), and provides a list of general projection parameters (6.2.3) it does not generally indicate what projection parameters are used for which projection methods, nor does it attempt to relate them to any other well known definitions such as EPSG.

I feel it is important to collect a list of projection parameters for each support projection method, and where possible to relate them back to EPSG method and parameter codes for clarity.

To some extent I have attempted to do so at http://www.remotesensing.org/geotiff/proj_list/ in a way relate connects GeoTIFF, PROJ.4, EPSG and OGC Well Known Text. For the purposes of the GeoTIFF specification I would suggest we stick to offering the GeoTIFF codes, and relating them back to EPSG while enumerating some projection methods and parameters support in GeoTIFF and not in EPSG and clarifying some situations that match poorly between GeoTIFF and EPSG.

**Comment by EmDevys** [comment]
This was previously issue #3 and it has been addressed in OGC GeoTIFF 1.1, by use of EPSG register, and documented in requirements and annexes.
GeoTIFF is not supposed to reinvent projection parameters, and to rely on standardized documentation of geodetic and projections parameters, such as EPSG.
Roger Lott strongly contributed to this effort.
=> recommend to reclose this issue.
