### ISSUE TITLE
Relationship to Newer EPSG Releases

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/geotiff#90]
The original GeoTIFF specification was based on the EPSG database in release at the time. Since then the EPSG database has grown and to a limited extent been refactored. While it was not exactly clear how this related to GeoTIFF the accepted industry practice has been to accept newer EPSG PCS and GCS codes even though they are not explicitly listed in the GeoTIFF specification (ie. sections 6.3.2, 6.3.3 and 6.3.4). It is suggested that this be codified into the GeoTIFF specification. We should also likely update sections 6.3.x to reflect a current set of codes or alternatively remove them in favor of a reference to EPSG with a few examples for clarification.

**Comment by EmDevys** [comment]
This issue was issue #2. and has been closed as addressed in revision 1.1. Also suppressed and deprecated values are documented in annexe G.
GeoTIFF 1.1 is now based on EPSG register.
=> proposal to re-close this issue.
